plot2 <- read.csv("household_power_consumption.txt",header = TRUE, sep = ";")
plot2$Date <- as.Date(plot2$Date, format="%d/%m/%Y")
requiredDate <- subset(plot2,plot2$Date == "2007-02-02" | plot2$Date == "2007-02-01")
requiredDate$Global_active_power <- as.numeric(as.character(requiredDate$Global_active_power))
#hist(as.numeric(requiredDate$Global_active_power),col="red",xlab="Global Active Power (kilowatts)", main=paste("Global Active Power"))
#dev.copy(png, file="plot2.png", width=480, height=480)
#dev.off()
requiredDate$Timestamp <-paste(requiredDate$Date, requiredDate$Time)
plot(strptime(requiredDate$Timestamp, "%Y-%m-%d %H:%M:%S"), requiredDate$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(kilowatts)")
dev.copy(png, file="plot2.png", width=480, height=480)
dev.off()