plot3 <- read.csv("household_power_consumption.txt",header = TRUE, sep = ";")
plot3$Date <- as.Date(plot3$Date, format="%d/%m/%Y")
requiredDate <- subset(plot3,plot3$Date == "2007-02-02" | plot3$Date == "2007-02-01")
requiredDate$Global_active_power <- as.numeric(as.character(requiredDate$Global_active_power))
requiredDate$Sub_metering_1 <- as.numeric(as.character(requiredDate$Sub_metering_1))
requiredDate$Sub_metering_2 <- as.numeric(as.character(requiredDate$Sub_metering_2))
requiredDate$Sub_metering_3 <- as.numeric(as.character(requiredDate$Sub_metering_3))
requiredDate$Timestamp <-paste(requiredDate$Date, requiredDate$Time)
with(requiredDate, plot(strptime(requiredDate$Timestamp,"%Y-%m-%d %H:%M:%S"),requiredDate$Sub_metering_1, type="n", xlab = "", ylab = "Energy Sub Metering"))
with(requiredDate, points(strptime(requiredDate$Timestamp,"%Y-%m-%d %H:%M:%S"),requiredDate$Sub_metering_1, col="black", type="l"))
with(requiredDate, points(strptime(requiredDate$Timestamp,"%Y-%m-%d %H:%M:%S"),requiredDate$Sub_metering_2, col="red", type="l"))
with(requiredDate, points(strptime(requiredDate$Timestamp,"%Y-%m-%d %H:%M:%S"),requiredDate$Sub_metering_3, col="blue", type="l"))
legend("topright", lty=1, col = c("black", "red", "blue"), 
       legend = c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"))
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()